package:
  name: pycompwa
  version: "0.2.0"

source:
  # git_url: https://github.com/ComPWA/pycompwa
  path: .

requirements:
  build:
    - ROOT
    - boost
    - cmake
    - packaging
    - python
    - scikit-build

  run:
    - python

build:
  script: python setup.py install

test:
  imports:
    -

about:
  home: https://pycompwa.readthedocs.io/en/latest/
  license: GNU General Public License
  license_family: GPL3
  summary: The common Partial Wave Analysis framework
