package:
  name: pycompwa
  version: "0.2.0"

source:
  git_url: https://github.com/ComPWA/pycompwa

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy 1.11.*

build:
  script: python setup.py install

test:
  imports:
    -

about:
  home: https://pycompwa.readthedocs.io/en/latest/
  license: GNU General Public License
  license_family: GPL3
  summary: The common Partial Wave Analysis framework
